Let the compiler decide on partial_ordering vs strong_ordering
This should fix the following build error with MSVC

  <...>\include\mdds\segment_tree.hpp(66,28): error C7549: 'mdds::segment_tree<float,`anonymous-namespace'::move_data>::segment_type::operator <=>': defaulted comparison function cannot be declared to return a comparison category stronger than the common category among bases and members which was deduced to be 'std::partial_ordering'